<div style="display: flex; align-items: center; justify-content: center; flex-wrap: wrap;">
    <div style="flex: 1; min-width: 250px; display: flex; justify-content: center;">
        <img src="https://adnova.novaims.unl.pt/media/22ui3ptm/logo.svg" style="max-width: 80%; height: auto; margin-top: 50px; margin-bottom: 50px;margin-left: 3rem;">
    </div>
    <div style="flex: 2; text-align: center; margin-top: 20px;margin-left: 8rem;">
        <div style="font-size: 28px; font-weight: bold; line-height: 1.2;">
            <span style='color:#6f800f'> Data Mining Project | </span>
            <span style='color:#393B79'>ABCDEats Inc.</span>
        </div>
        <div style="font-size: 17px; font-weight: bold; margin-top: 10px;">
            Fall Semester | 2024 - 2025
        </div>
        <div style="font-size: 17px; font-weight: bold;">
            Master in Data Science and Advanced Analytics
        </div>
        <div style="margin-top: 20px;">
            <div>AndrÃ© Silvestre, 20240502</div>
            <div>Filipa Pereira, 20240509</div>
            <div>Umeima Mahomed, 20240543</div>
        </div>
        <div style="margin-top: 20px; font-weight: bold;">
            Group 37
        </div>
    </div>
</div>

<div style="background: linear-gradient(to right,#6f800f, #393B79); 
            padding: .7px; color: white; border-radius: 300px; text-align: center;">
</div>

## **ðŸ“š Libraries Import**

In [1]:
# For data
import pandas as pd
import numpy as np
import os

# For plotting and EDA
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import matplotlib.lines as mlines
from matplotlib.colors import LinearSegmentedColormap

# For preprocessing
from sklearn.preprocessing import StandardScaler

# Set the style of the visualization
pd.set_option('display.max_columns', None)                  # display all columns
pd.set_option('display.float_format', lambda x: '%.2f' % x) # display floats with 2 decimal places

# for better resolution plots
%config InlineBackend.figure_format = 'retina' # optionally, you can change 'svg' to 'retina'

# Setting seaborn style
plt.style.use('ggplot')
sns.set_theme(style='white')

# <a class='anchor' id='2'></a>
<br>
<style>
@import url('https://fonts.cdnfonts.com/css/avenir-next-lt-pro?styles=29974');
</style>

<div style="background: linear-gradient(to right, #6f800f,#393B79); 
            padding: 10px; color: white; border-radius: 300px; text-align: center;">
    <center><h1 style="margin-left: 140px;margin-top: 10px; margin-bottom: 4px; color: white;
                       font-size: 32px; font-family: 'Avenir Next LT Pro', sans-serif;">
        <b>Part 2 | Cluster Analysis </b></h1></center>
</div>

## **ðŸ§® Import Data**

In [9]:
#pip install pyarrow

In [6]:
# Importing the dataset after the preprocessing
ABCDEats = pd.read_parquet('data/DM2425_ABCDEats_1stPart.parquet')

In [7]:
# Display the first 5 rows just to confirm the import was successful
ABCDEats.head()

Variables,customer_id,customer_region,customer_age,vendor_count,product_count,is_chain,first_order,last_order,last_promo,payment_method,CUI_American,CUI_Asian,CUI_Beverages,CUI_Cafe,CUI_Chicken Dishes,CUI_Chinese,CUI_Desserts,CUI_Healthy,CUI_Indian,CUI_Italian,CUI_Japanese,CUI_Noodle Dishes,CUI_OTHER,CUI_Street Food / Snacks,CUI_Thai,DOW_0,DOW_1,DOW_2,DOW_3,DOW_4,DOW_5,DOW_6,HR_0,HR_1,HR_2,HR_3,HR_4,HR_5,HR_6,HR_7,HR_8,HR_9,HR_10,HR_11,HR_12,HR_13,HR_14,HR_15,HR_16,HR_17,HR_18,HR_19,HR_20,HR_21,HR_22,HR_23,order_count,customer_region_buckets,customer_age_group,days_between_orders,days_between_orders_per_order,last_promo_bin,CUI_Total_Amount_Spent,CUI_Most_Spent_Cuisine,CUI_Total_Food_Types,CUI_Avg_Amount_Spent
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,1b8f824d5e,2360,18.00,2,5,1,0.00,1,DELIVERY,DIGI,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,28.88,0.00,0.00,0.00,0.00,0.00,0.00,1,0,0,0,0,0,1,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2,2,15-28,1.00,0.50,1,28.88,Indian,1,14.44
1,5d272b9dcb,8670,17.00,2,2,2,0.00,1,DISCOUNT,DIGI,12.82,6.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1,0,0,0,0,0,1,0.00,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,2,8,15-28,1.00,0.50,1,19.21,American,2,9.61
2,f6d1b2ba63,4660,38.00,1,2,2,0.00,1,DISCOUNT,CASH,9.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1,0,0,0,0,0,1,0.00,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,4,29-41,1.00,0.50,1,9.20,American,1,4.60
3,180c632ed8,4660,NaN,2,3,1,0.00,2,DELIVERY,DIGI,0.00,13.70,0.00,0.00,0.00,0.00,0.00,0.00,17.86,0.00,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,1,0.00,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2,4,None,2.00,1.00,1,31.56,Indian,2,15.78
4,4eb37a6705,4660,20.00,2,5,0,0.00,2,NO PROMO,DIGI,14.57,40.87,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,1,0.00,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,15-28,2.00,1.00,0,55.44,Asian,2,27.72

In [8]:
# Number of rows and columns
print('Number of\033[1m rows \033[0m:', ABCDEats.shape[0])
print('Number of\033[1m columns \033[0m:', ABCDEats.shape[1])

Number of rows : 31737
Number of columns : 66

In [10]:
# Check for missing values in the dataset (n = number of missing values & % = percentage of missing values)
NAs_df = pd.DataFrame({'n NAs': ABCDEats.isnull().sum(), 
                       '% NAs': round(ABCDEats.isnull().mean() * 100,2)})
NAs_df.index.name = 'Variables'

# Display the variables with missing values
NAs_df[NAs_df['n NAs'] > 0]

                               n NAs  % NAs
Variables
customer_age                     727   2.29
first_order                      106   0.33
HR_0                            1164   3.67
customer_age_group               727   2.29
days_between_orders              106   0.33
days_between_orders_per_order    106   0.33

---

In [15]:
# Filtrar os casos onde customer_age estÃ¡ missing e not missing
missing_customer_age = ABCDEats[ABCDEats['customer_age'].isnull()]
not_missing_customer_age = ABCDEats[ABCDEats['customer_age'].notnull()]

# Calcular as mÃ©dias para ambos os casos
mean_missing = missing_customer_age.mean(numeric_only=True)
mean_not_missing = not_missing_customer_age.mean(numeric_only=True)

# Comparar as mÃ©dias
comparison = pd.DataFrame({
    "Mean_Customer_Age_Missing": mean_missing,
    "Mean_Customer_Age_Not_Missing": mean_not_missing
})

# Mostrar os resultados
comparison

,Mean_Customer_Age_Missing,Mean_Customer_Age_Not_Missing
Variables,,
customer_age,NaN,27.51
vendor_count,3.17,3.11
product_count,5.95,5.69
is_chain,3.00,2.83
first_order,27.51,28.42
last_order,65.17,63.72
CUI_American,4.86,4.90
CUI_Asian,10.89,9.98
CUI_Beverages,2.34,2.31
CUI_Cafe,1.21,0.80
CUI_Chicken Dishes,0.86,0.77
CUI_Chinese,1.46,1.44
CUI_Desserts,1.16,0.88
CUI_Healthy,0.96,0.95
CUI_Indian,1.57,1.64
CUI_Italian,2.93,3.26
CUI_Japanese,2.98,3.01
CUI_Noodle Dishes,0.68,0.72
CUI_OTHER,3.21,3.01
CUI_Street Food / Snacks,4.01,3.93
CUI_Thai,1.26,0.84
DOW_0,0.59,0.56
DOW_1,0.55,0.57
DOW_2,0.60,0.59
DOW_3,0.62,0.62
DOW_4,0.73,0.68
DOW_5,0.72,0.65
DOW_6,0.77,0.71
HR_0,0.00,0.00
HR_1,0.06,0.05
HR_2,0.07,0.06
HR_3,0.12,0.12
HR_4,0.13,0.10
HR_5,0.08,0.08
HR_6,0.07,0.07
HR_7,0.08,0.08
HR_8,0.14,0.13
HR_9,0.26,0.23
HR_10,0.36,0.33
HR_11,0.37,0.38
HR_12,0.33,0.32
HR_13,0.23,0.24
HR_14,0.22,0.22
HR_15,0.32,0.28
HR_16,0.36,0.36
HR_17,0.42,0.39
HR_18,0.33,0.34
HR_19,0.29,0.25
HR_20,0.14,0.14
HR_21,0.06,0.07
HR_22,0.04,0.05
HR_23,0.05,0.05
order_count,4.57,4.38
days_between_orders,37.84,35.52
days_between_orders_per_order,8.92,8.50
last_promo_bin,0.43,0.47
CUI_Total_Amount_Spent,40.38,38.42
CUI_Total_Food_Types,2.30,2.28
CUI_Avg_Amount_Spent,9.99,10.31